---
# Add new user and add him to groups
#
- hosts: my_servers
  become: true
  tasks:
    - name: Add new user MY_USER
      user:
        name: "{{ item.name }}"
        comment: "{{ item.comment }}"
        password: "{{ item.password }}"
#        state: absent
      with_items:
          - { name: 'MY_USER', comment: 'My User, my_email@mail.com, role-sysadmin, task #123', password: '$IwA4GLdfK1111111111/KleIV.oY3TfTjvjTnrUt7dysMHoqSn9' }

    - name: Add to admin_group
      user:
        name: MY_USER
        groups: admin_group
#        state: absent
        append: yes

    - name: Add to db_group
      user:
        name: MY_USER
        groups: db_group
#        state: absent
        append: yes


    - name: Add to sshusers
      user:
        name: MY_USER
        groups: sshusers
#        state: absent
        append: yes
